name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
    - uses: actions-rust-lang/setup-rust-toolchain@ac4326d13dde1d6594dbfcb05f9bdb7d8879be6e
      with:
        toolchain: nightly
    - name: Build
      run: cargo build --verbose

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
    - uses: actions-rust-lang/setup-rust-toolchain@ac4326d13dde1d6594dbfcb05f9bdb7d8879be6e
      with:
        toolchain: nightly
        components: clippy
    - name: Linter
      run: cargo clippy -- -D clippy::cargo -D clippy::pedantic -D clippy::nursery -D clippy::alloc_instead_of_core -D missing_debug_implementations -D clippy::expect_used -A clippy::cast_lossless -A clippy::redundant_else -A clippy::multiple_crate_versions -A clippy::cargo_common_metadata -D unused_variables

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
    - uses: actions-rust-lang/setup-rust-toolchain@ac4326d13dde1d6594dbfcb05f9bdb7d8879be6e
      with:
        toolchain: nightly
    - name: Run tests
      run: cargo test --verbose

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - uses: actions-rs/toolchain@8e603f32c5c6eeca5b1b2d9d1e7464d926082f1d
        with:
          toolchain: nightly
          override: true

      - uses: aig787/cargo-udeps-action@v1
        with:
          version: 'latest'
          args: '--all-targets'

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
